name: Pipeline

on: [push]

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # The "Build with Maven" step runs the Maven `package` target in non-interactive mode to ensure that your code builds, tests pass, and a package can be created.
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Running tests with Maven
        run: mvn test